[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  revision = "e3fb1a1acd7605367a2b378bc2e2f893c05174b7"
  name = "github.com/prometheus/common"
